&CONTROL
 restart_mode='from_scratch',
 wf_collect=.true.,
 
 nstep = 100,
  calculation = 'vc-relax'
  prefix = 'ZrH6Pt'
  outdir = './tmp/'
  pseudo_dir='/home/marco/ZOS_Cloud_Compute/pseudo/'
  forc_conv_thr = 1.0d-3
  tstress = .true.
  tprnfor = .true.
/
&SYSTEM
  ibrav = 0
  nat = 8
  ntyp = 3
  ecutwfc = 40.0
  ecutrho = 320.0
  occupations = 'smearing'
  smearing = 'methfessel-paxton'
  degauss = 0.02
/
&ELECTRONS
 mixing_beta = 0.4,
 electron_maxstep = 300,
 mixing_mode='plain',
 mixing_ndim = 6,
 diagonalization='cg',
  conv_thr = 1.0d-6
/
&IONS
  ion_dynamics = 'bfgs'
/
&CELL
  cell_dynamics = 'bfgs'
  press = 0.0
/
ATOMIC_SPECIES
  H  1.00  H.UPF
  Pt  1.00  Pt.UPF
  Zr  1.00  Zr.UPF
ATOMIC_POSITIONS (angstrom)
  H  1.381778  0.797757  0.721953
  H  3.566813  0.797754  0.721953
  H  2.474294  2.690036  0.721953
  H  3.601323  -0.777852  2.165860
  H  1.347272  -0.777851  2.165860
  H  2.474299  -2.729870  2.165860
  Pt  2.474297  1.428521  2.165860
  Zr  2.474298  -1.428510  0.721953
K_POINTS automatic
  2 2 2 0 0 0
CELL_PARAMETERS (angstrom)
  2.474300  -4.285540  0.000000
  2.474294  4.285537  -0.000000
  0.000000  -0.000000  2.887813

! SMART_OOM_LEVEL=4
