&CONTROL
 restart_mode='from_scratch',
 wf_collect=.true.,
  calculation = 'vc-relax'
  prefix = 'TiH2'
  outdir = './tmp/'
  pseudo_dir='/home/marco/ZOS_Cloud_Compute/pseudo/'
  forc_conv_thr = 1.0d-3
  tstress = .true.
  tprnfor = .true.
/
&SYSTEM
 nosym=.true.,
  ibrav = 0
  nat = 3
  ntyp = 2
  ecutwfc = 40.0
  ecutrho = 320.0
  occupations = 'smearing'
  smearing = 'methfessel-paxton'
  degauss = 0.02
/
&ELECTRONS
 electron_maxstep = 150,
 mixing_ndim = 8,
 diagonalization='david',
  conv_thr = 1.0d-6
/
&IONS
  ion_dynamics = 'bfgs'
/
&CELL
  cell_dynamics = 'bfgs'
  press = 0.0
/
ATOMIC_SPECIES
  H  1.00  H.UPF
  Ti  1.00  Ti.UPF
ATOMIC_POSITIONS (angstrom)
  Ti  0.000000  -0.000000  -0.000000
  H  2.701113  1.909976  4.678464
  H  0.900371  0.636659  1.559488
K_POINTS automatic
  2 2 2 0 0 0
CELL_PARAMETERS (angstrom)
  2.701113  0.000000  1.559488
  0.900371  2.546634  1.559488
  0.000001  0.000000  3.118977

! SMART_OOM_LEVEL=0
